[env:waveshare_esp32s3_eth]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

board_build.partitions = huge_app.csv
board_build.flash_mode = dio
board_build.arduino.memory_type = qio_opi

build_flags =
  -DBOARD_HAS_PSRAM
  -DCORE_DEBUG_LEVEL=3

lib_ldf_mode = deep+

lib_deps =
  ArduinoJson
  Ethernet2
  ReadyMail
  ESP_SSLClient
  EspUsbHost
  knolleary/PubSubClient
  openslab-osu/SSLClient

build_unflags =
    -std=gnu++11

build_type = release

